server:
  port: 2222
spring:
  application:
    name: redis-lock
  redis:
    database: 0
    host: 1.15.72.181
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: '6623'
    port: 6379

eureka:
  instance:
    instance-id: redis-lock02
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/