server:
  port: 1111
spring:
  redis:
    database: 0
    host: 1.15.72.181
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: '6623'
    port: 6379
