server:
  port: 6611

eureka:
  instance:
    instance-id: gateway6611
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启注册中心动态创建路由功能
      routes:
        #这个配置的意思是：访问gateway-host/red/xxx或者gateway-host/blue/xxx的话，
        #这个请求会转发到https://example.org，相当于https://example.org/red/xxx或https://example.org/blue/xxx,实现了一个转发的功能。
        - id: host_route
          uri: https://example.org
          predicates:
            - Path=/red/{segment},/blue/{segment}
        # 这个配置的意思是：访问localhost:6611/order/**时，这个请求会转发到localhost:80/order/**
        - id: order80
          uri: lb://order #lb表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/order/**






